[build]
builder = "nixpacks"

[build.commands]
install = "npm install --legacy-peer-deps"
build = "npm run build"

[start]
command = "npx serve -s build -l 3000"

[deploy]
startCommand = "npx serve -s build -l 3000"
